services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads      # для файлов отчётов
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  worker:
    build: ./backend
    container_name: worker
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '55432:5432'